version: '3'
services:
  client:
    image: ${REPO}/${IMAGE}:${TAG}
    depends_on:
      - server-01
      - server-02
    ports:
      - "${PORT}/${PROTOCOL}"
    environment:
      - ROLE=client
      - SERVER_ADDR=${MULTICAST}
    command: -u --ttl ${TTL} -t ${TIME} -l ${LENGTH} -w ${WINDOW} -b ${BANDWIDTH} -F ${FILE}

  server-01:
    image: ${REPO}/${IMAGE}:${TAG}
    ports:
      - "${PORT}/${PROTOCOL}"
    environment:
      - ROLE=server
    command: -u -B ${MULTICAST} -l ${LENGTH} -w ${WINDOW} -i ${INTERVAL}
  server-02:
    image: ${REPO}/${IMAGE}:${TAG}
    ports:
      - "${PORT}/${PROTOCOL}"
    environment:
      - ROLE=server
    command: -u -B ${MULTICAST} -l ${LENGTH} -w ${WINDOW} -i ${INTERVAL}
...