version: '3'
services:
  client:
    image: ${REPO}/${IMAGE}:${TAG}
    depends_on:
      - server-01
      - server-02
    ports:
      - "5001/udp"
    environment:
      - ROLE=client
      - SERVER_ADDR=${MULTICAST}
    command: -u --ttl ${TTL} -t ${TIME} -L ${LENGTH} -b ${BANDWIDTH} -F ${FILE}

  server-01:
    image: ${REPO}/${IMAGE}:${TAG}
    ports:
      - "5001/udp"
    environment:
      - ROLE=server
    command: -u -B ${MULTICAST} -i ${INTERVAL}
  server-02:
    image: ${REPO}/${IMAGE}:${TAG}
    ports:
      - "5001/udp"
    environment:
      - ROLE=server
    command: -u -B ${MULTICAST} -i ${INTERVAL}
...