apiVersion: batch/v1
kind: Job
metadata:
  name: multicast-iperf
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: multicast-iperf
    spec:
      hostNetwork: true
      containers:
      - name: iperf-container
        image: devopsman/multicast-iperf:ocp-02
        env:
        - name: ROLE
          value: "client"
        - name: SERVER_ADDR
          value: "192.168.99.102"
        - name: TTL
          value: "2"
        - name: LENGTH
          value: "2K"
        - name: WINDOW
          value: "8K"
        - name: BANDWIDTH
          value: "100K"
        - name: UDP
          value: "u"
        - name: BIND
          value: "224.0.0.1"
      restartPolicy: OnFailure
      activeDeadlineSeconds: 30