apiVersion: v1
kind: Pod
metadata:
  name: multicast-iperf
  labels:
    app: iperf
spec:
  hostNetwork: true
  containers:
  - name: iperf-container
    image: devopsman/multicast-iperf:ocp-04
    env:
    - name: ROLE
      value: "client"
    - name: SERVER_ADDR
      value: "224.0.0.1"
    - name: TTL
      value: "2"
    - name: LENGTH
      value: "2K"
    - name: WINDOW
      value: "8K"
    - name: BANDWIDTH
      value: "1M"
    - name: UDP
      value: "u"
#    - name: BIND
#      value: "239.1.0.0"
  restartPolicy: OnFailure
